@id = ef73acd6-e13d-487d-b438-9db57dcd10d3
PUT http://localhost:5132/breakfast/{{id}}
Content-Type: application/json

{
    "name":"vegan chick OwO",
    "description":"looks weird, but seems edible",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}